# Use an official Node runtime as a base image
FROM node:20-alpine as build

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular app for production
RUN npm run build

# Use Nginx to serve the Angular app
FROM nginx:alpine

# Copy the built app from the previous stage into the NGINX html directory
COPY --from=build /usr/src/app/dist/frontend /usr/share/nginx/html/

# Expose port 80 to the outside world
EXPOSE 80

# Command to run NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]
