version: '3.9'

services:

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes: 
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: db_v1
    container_name: postgres_db1

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - backend/.env.uat
    container_name: backend
    depends_on:
      - db
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: frontend
volumes:
  db_data: